PRODUCT_PACKAGES += \
                    libnvos \
                    libclcore_nvidia \
                    camera.tegra132 \
                    libnvddk_2d \
                    libnvddk_2d_v2 \
                    libnvrm \
                    libnvrm_graphics \
                    libnvddk_vic \
                    libnvgr \
                    libnvmm_utils \
                    libnvavp \
                    libnvtvmr \
                    libnvcam_imageencoder \
                    libnvmm \
                    libnvisp_v3 \
                    libnvmm_camera_v3 \
                    libnvodm_imager \
                    libnvvicsi_v3 \
                    libopencv24_tegra \
                    gralloc.tegra132 \
                    libnvblit \
                    hwcomposer.tegra132 \
                    libtsechdcp \
                    gatekeeper.flounder \
                    keystore.flounder \
                    memtrack.tegra132 \
                    tlk_daemon \
                    libEGL_tegra \
                    libnvglsi \
                    libnvrmapi_tegra \
                    libGLESv1_CM_tegra \
                    libglcore \
                    libGLESv2_tegra \
                    libnvwsi \
                    libnvmm_audio \
                    libnvmm_parser \
                    libnvmm_contentpipe \
                    libnvmm_writer \
                    libnvmmlite_audio \
                    libnvmmlite_utils \
                    libnvmmlite \
                    libnvmmlite_image \
                    libnvparser \
                    libnvmmlite_video \
                    libnvmmlite_msaudio \
                    libnvmm_aviparser \
                    libnvmm_asfparser \
                    libnvtnr \
                    libnvomx \
                    libnvomxilclient \
                    libnvRSCompiler \
                    libnvRSDriver \
                    libnvptx \
                    libnvcms \
                    libnvapputil \
                    libmdmdetect \
                    libfrsdk \
                    tegrastats \
                    libperipheral_client \
                    libLifevibes_lvverx \
                    libLifevibes_lvvetx \
                    libnvcamerahdr \
                    libnvodm_query \
                    libnvcapclk \
                    libnvfusebypass \
                    libnvsm \
                    LMspeed_508 \
                    PFFprec_600 \
                    libnvcompute \
                    libstagefrighthw \
                    liboemcrypto \
                    libwvdrmengine \
                    libdrmwvmplugin \
                    libtlk_secure_hdcp_up 
