PRODUCT_PACKAGES += \
                    libnvos \
                    libnvoice \
                    libnvaudiofx \
                    camera.tegra \
                    libnvddk_2d_v2 \
                    libnvrm \
                    libnvrm_graphics \
                    libnvddk_vic \
                    libnvgr \
                    libnvmm_utils \
                    libnvavp \
                    libnvtvmr \
                    libnvcam_imageencoder \
                    libnvmm \
                    libscf \
                    libnvcamlog \
                    libnvcamerautils \
                    libcuda \
                    libphs \
                    libnvrm_gpu \
                    libnvisp_v3 \
                    libnvmm_camera_v3 \
                    libnvodm_imager \
                    libnvvicsi_v3 \
                    libopencv24_tegra \
                    libtbb \
                    libnvfnet \
                    libnvfnetstorehdfx \
                    libnvfnetstoredefog \
                    libnvcamerahdr_v3 \
                    libnvcameranrr \
                    libnvcudautils \
                    gralloc.tegra \
                    libnvblit \
                    hwcomposer.tegra \
                    libnvhwc_service \
                    libtlk_secure_hdcp_up \
                    libtsechdcp \
                    keystore.tegra \
                    memtrack.tegra \
                    vulkan.tegra \
                    tlk_daemon \
                    ss_status \
                    ts.default \
                    libEGL_tegra \
                    libtsec_wrapper \
                    libnvglsi \
                    libnvrmapi_tegra \
                    libnvcpl \
                    libGLESv1_CM_tegra \
                    libglcore \
                    libGLESv2_tegra \
                    libnvRSDriver \
                    libnvRSCompiler \
                    libnvwsi \
                    libnvmm_audio \
                    libnvmm_msaudio \
                    libnvmm_parser \
                    libnvmm_contentpipe \
                    libnvmm_writer \
                    libnvmmlite_audio \
                    libnvmmlite_utils \
                    libnvmmlite \
                    libnvmmlite_image \
                    libnvparser \
                    libnvmmlite_video \
                    libnvtnr \
                    libnvomx \
                    libnvomxadaptor \
                    libnvomxilclient
